"""ScaleScore core scoring and analysis modules."""

from scalescore.core.exceptions import (
    AssessmentExistsError,
    AssessmentNotFoundError,
    AssessmentProcessingError,
    AuthenticationError,
    AuthorizationError,
    ConfigurationError,
    CSVFormatError,
    DatabaseError,
    EntityNotFoundError,
    ErrorCode,
    InvalidFieldValueError,
    MissingRequiredFieldError,
    MultipleOrganizationsError,
    OrganizationNotFoundError,
    OrganizationRequiredError,
    ScaleScoreError,
    TenantAccessDeniedError,
    ValidationError,
)

__all__ = [
    "AssessmentExistsError",
    "AssessmentNotFoundError",
    "AssessmentProcessingError",
    "AuthenticationError",
    "AuthorizationError",
    "ConfigurationError",
    "CSVFormatError",
    "DatabaseError",
    "EntityNotFoundError",
    "ErrorCode",
    "InvalidFieldValueError",
    "MissingRequiredFieldError",
    "MultipleOrganizationsError",
    "OrganizationNotFoundError",
    "OrganizationRequiredError",
    "ScaleScoreError",
    "TenantAccessDeniedError",
    "ValidationError",
]
