# Generated by scripts/generate_bindings.py; DO NOT EDIT.
from __future__ import annotations

from typing import Annotated, Literal, Self

from jsonschema import FormatChecker
from jsonschema.exceptions import FormatError
from pydantic import AfterValidator, BaseModel, ConfigDict, Field, StrictStr, model_validator


class TransportModel(BaseModel):
    model_config = ConfigDict(extra="forbid", strict=True)


_FORMAT_CHECKER = FormatChecker()


def _validate_date_time(value: str) -> str:
    try:
        _FORMAT_CHECKER.check(value, "date-time")
    except FormatError as error:
        raise ValueError("must be an RFC 3339 date-time string") from error
    return value


DateTimeString = Annotated[StrictStr, AfterValidator(_validate_date_time)]


class WorkflowRefMetadata(TransportModel):
    ref_id: StrictStr = Field(min_length=1)
    ref_type: Literal["workflow"]
    source_capability: Literal["workflow_context"]
    organization_id: StrictStr = Field(min_length=1)
    environment_id: StrictStr = Field(min_length=1)
    external_uri: StrictStr = Field(min_length=1)
    snapshot_id: StrictStr = Field(min_length=1)
    version: StrictStr = Field(min_length=1)


class WorkflowRefEnvelope(TransportModel):
    contract_version: Literal["proofhouse-shared-contracts/v0.1"]
    contract_name: Literal["WorkflowRef"]
    producer_capability: Literal["workflow_context"]
    producer_system: Literal["proofhouse-workflow-context"]
    canonical_owner: Literal["workflow_context"]
    issued_at: DateTimeString
    cache_policy: Literal["summary_snapshot"]
    ref: WorkflowRefMetadata


class AssessmentRef(TransportModel):
    ref_id: StrictStr = Field(pattern=r"^assessment:.+$")
    ref_type: Literal["assessment"]
    source_capability: Literal["readiness"]
    organization_id: StrictStr = Field(min_length=1)
    environment_id: StrictStr = Field(min_length=1)
    external_uri: StrictStr = Field(min_length=1)
    snapshot_id: StrictStr = Field(min_length=1)
    version: StrictStr = Field(min_length=1)
    created_at: DateTimeString
    summary: StrictStr = Field(min_length=1)
    assessment_id: StrictStr = Field(min_length=1)
    workflow_ref: WorkflowRefEnvelope
    assessment_type: Literal["workflow_readiness", "operational_learning_suitability"]
    score: float = Field(ge=0, le=100)
    grade: Literal["A", "B", "C", "D", "F"]
    status: Literal["ready", "watch", "at_risk", "blocked"]
    top_blockers: list[Annotated[StrictStr, Field(min_length=1)]] = Field(max_length=5)
    top_reasons: list[Annotated[StrictStr, Field(min_length=1)]] = Field(max_length=5)

    @model_validator(mode="after")
    def validate_semantic_invariants(self) -> Self:
        expected_grade = (
            "A"
            if self.score >= 90
            else "B"
            if self.score >= 80
            else "C"
            if self.score >= 70
            else "D"
            if self.score >= 60
            else "F"
        )
        if self.grade != expected_grade:
            raise ValueError(f"grade must be {expected_grade} for score {self.score:g}")
        expected_status = (
            "ready"
            if self.score >= 80
            else "watch"
            if self.score >= 65
            else "at_risk"
            if self.score >= 50
            else "blocked"
        )
        if self.status != expected_status:
            raise ValueError(f"status must be {expected_status} for score {self.score:g}")
        if self.workflow_ref.ref.organization_id != self.organization_id:
            raise ValueError(
                "workflow_ref.ref.organization_id must equal ref.organization_id"
            )
        return self


class AssessmentRefEnvelope(TransportModel):
    contract_version: Literal["proofhouse-shared-contracts/v0.1"]
    contract_name: Literal["AssessmentRef"]
    producer_capability: Literal["readiness"]
    producer_system: Literal["proofhouse-readiness"]
    canonical_owner: Literal["readiness"]
    issued_at: DateTimeString
    cache_policy: Literal["summary_snapshot"]
    ref: AssessmentRef
