# Generated by scripts/generate_bindings.py; DO NOT EDIT.
from __future__ import annotations

from typing import Annotated, Literal, Self

from jsonschema import FormatChecker
from jsonschema.exceptions import FormatError
from pydantic import AfterValidator, BaseModel, ConfigDict, Field, StrictStr, model_validator


class TransportModel(BaseModel):
    model_config = ConfigDict(extra="forbid", strict=True)


_FORMAT_CHECKER = FormatChecker()


def _validate_date_time(value: str) -> str:
    try:
        _FORMAT_CHECKER.check(value, "date-time")
    except FormatError as error:
        raise ValueError("must be an RFC 3339 date-time string") from error
    return value


DateTimeString = Annotated[StrictStr, AfterValidator(_validate_date_time)]
IdentityString = Annotated[
    StrictStr,
    Field(pattern=r"^[A-Za-z0-9][A-Za-z0-9._:-]*$", max_length=256),
]
ImmutablePin = Annotated[
    StrictStr,
    Field(pattern=r"^[A-Za-z0-9][A-Za-z0-9._:+-]*$", max_length=256),
]


class WorkflowRefMetadata(TransportModel):
    ref_id: StrictStr = Field(pattern=r"^workflow:[A-Za-z0-9][A-Za-z0-9._:-]*$")
    ref_type: Literal["workflow"]
    source_capability: Literal["workflow_context"]
    organization_id: IdentityString
    environment_id: IdentityString
    external_uri: StrictStr = Field(min_length=1)
    snapshot_id: ImmutablePin | None = None
    version: ImmutablePin | None = None
    workflow_id: IdentityString

    @model_validator(mode="after")
    def require_immutable_identity(self) -> Self:
        if self.snapshot_id is None and self.version is None:
            raise ValueError("snapshot_id or version is required")
        return self


class WorkflowRefEnvelope(TransportModel):
    contract_version: Literal["proofhouse-shared-contracts/v0.1"]
    contract_name: Literal["WorkflowRef"]
    producer_capability: Literal["workflow_context"]
    producer_system: Literal["proofhouse-workflow-context"]
    canonical_owner: Literal["workflow_context"]
    issued_at: DateTimeString
    cache_policy: Literal["summary_snapshot"]
    ref: WorkflowRefMetadata


class ControlRef(TransportModel):
    ref_id: StrictStr = Field(pattern=r"^control:[A-Za-z0-9][A-Za-z0-9._:-]*$")
    ref_type: Literal["control"]
    source_capability: Literal["workflow_context"]
    organization_id: IdentityString
    environment_id: IdentityString
    external_uri: StrictStr = Field(min_length=1)
    snapshot_id: ImmutablePin | None = None
    version: ImmutablePin | None = None
    created_at: DateTimeString
    summary: StrictStr = Field(min_length=1, max_length=500)
    control_assignment_id: IdentityString
    control_id: IdentityString
    control_key: StrictStr = Field(min_length=1, max_length=128)
    control_family: StrictStr = Field(min_length=1, max_length=128)
    workflow_id: IdentityString
    workflow_ref: WorkflowRefEnvelope
    implementation_state: Literal["planned", "in_progress", "implemented", "waived"]
    linkage_state: Literal["missing", "linked", "verified", "not_applicable"]

    @model_validator(mode="after")
    def validate_semantic_invariants(self) -> Self:
        if self.snapshot_id is None and self.version is None:
            raise ValueError("snapshot_id or version is required")
        workflow = self.workflow_ref.ref
        for field in ("organization_id", "environment_id", "workflow_id"):
            if getattr(workflow, field) != getattr(self, field):
                raise ValueError(f"workflow_ref.ref.{field} must equal ref.{field}")
        return self


class ControlRefEnvelope(TransportModel):
    contract_version: Literal["proofhouse-shared-contracts/v0.1"]
    contract_name: Literal["ControlRef"]
    producer_capability: Literal["workflow_context"]
    producer_system: Literal["proofhouse-workflow-context"]
    canonical_owner: Literal["workflow_context"]
    issued_at: DateTimeString
    cache_policy: Literal["summary_snapshot"]
    ref: ControlRef
